/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Cw20.types";
import * as _1 from "./Cw20.client";
import * as _2 from "./Cw20.react-query";
export namespace contracts {
  export const Cw20 = { ..._0,
    ..._1,
    ..._2
  };
}